package com.pai.api.catalog.service;
import java.time.Instant; import java.util.*; import jakarta.persistence.EntityManager; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.pai.api.catalog.dto.*; import com.pai.api.catalog.entity.*; import com.pai.api.catalog.repository.*; import com.pai.api.identity.service.*; import com.pai.api.shared.exceptions.*;
@Service public class InstitutionVaccineService {
 private final InstitutionVaccineRepository relations; private final InstitutionVaccineOptionRepository local; private final VaccineRepository vaccines; private final VaccineOptionTemplateRepository templates; private final IdentityService identity; private final DataScope scope; private final EntityManager em;
 public InstitutionVaccineService(InstitutionVaccineRepository r,InstitutionVaccineOptionRepository l,VaccineRepository v,VaccineOptionTemplateRepository t,IdentityService i,DataScope s,EntityManager e){relations=r;local=l;vaccines=v;templates=t;identity=i;scope=s;em=e;}
 private AuthorizedUser actor(UUID id,String p){AuthorizedUser a=identity.resolve(id);if(!a.getPermissions().contains(p))throw new PermissionDeniedException("Permiso insuficiente: "+p);return a;}
 private UUID institution(AuthorizedUser a,UUID requested){return scope.resolveInstitutionId(a,requested);}
 @Transactional(readOnly=true) public List<InstitutionVaccineResponse> list(UUID actorId,UUID inst){AuthorizedUser a=actor(actorId,"CATALOG_CONFIG_READ");UUID i=institution(a,inst);return relations.findByInstitutionId(i).stream().map(x->{VaccineEntity v=vaccines.findById(x.getVaccineId()).orElseThrow(()->new IllegalArgumentException("Vacuna no existe."));return new InstitutionVaccineResponse(x.getId(),i,v.getId(),v.getName(),v.getCode(),v.getCategory(),x.isEnabled(),x.getVersion());}).toList();}
 @Transactional public void enable(UUID actorId,UUID inst,UUID vaccine){AuthorizedUser a=actor(actorId,"CATALOG_CONFIG_WRITE");UUID i=institution(a,inst);VaccineEntity v=vaccines.findById(vaccine).orElseThrow(()->new IllegalArgumentException("Vacuna no existe."));if(!v.isActive())throw new IllegalArgumentException("La vacuna esta inactiva.");List<?> inserted=em.createNativeQuery("INSERT INTO app.institution_vaccines(institution_id,vaccine_id,is_enabled,enabled_at,enabled_by) VALUES (:i,:v,true,now(),:a) ON CONFLICT (institution_id,vaccine_id) DO NOTHING RETURNING id").setParameter("i",i).setParameter("v",vaccine).setParameter("a",a.getId()).getResultList();if(!inserted.isEmpty())for(VaccineOptionTemplateEntity t:templates.findByVaccineIdAndActiveTrueOrderBySortOrderAscDisplayNameAsc(vaccine)) local.save(new InstitutionVaccineOptionEntity(UUID.randomUUID(),i,vaccine,t.getFieldType(),t.getValue(),t.getDisplayName(),t.getSortOrder(),false,t.getId(),a.getId(),Instant.now()));else relations.findByInstitutionIdAndVaccineId(i,vaccine).ifPresent(x->{if(!x.isEnabled())em.createQuery("update InstitutionVaccineEntity x set x.enabled=true where x.id=:id").setParameter("id",x.getId()).executeUpdate();});}
 @Transactional public void disable(UUID actorId,UUID inst,UUID vaccine){AuthorizedUser a=actor(actorId,"CATALOG_CONFIG_WRITE");UUID i=institution(a,inst);relations.findByInstitutionIdAndVaccineId(i,vaccine).ifPresent(x->em.createQuery("update InstitutionVaccineEntity y set y.enabled=false where y.id=:id").setParameter("id",x.getId()).executeUpdate());}
  @Transactional(readOnly=true) public List<OptionResponse> options(UUID actorId,UUID inst,UUID vaccine){AuthorizedUser a=actor(actorId,"CATALOG_CONFIG_READ");UUID i=institution(a,inst);requireEnabled(i,vaccine);return local.findByInstitutionIdAndVaccineIdAndActiveTrueOrderBySortOrderAscDisplayNameAsc(i,vaccine).stream().map(x->new OptionResponse(x.getId(),vaccine,i,x.getFieldType(),x.getValue(),x.getDisplayName(),x.getSortOrder(),x.isDefault(),x.isActive(),x.getSourceTemplateId(),x.getVersion())).toList();}
 @Transactional public OptionResponse createOption(UUID actorId,UUID inst,UUID vaccine,OptionRequest r){AuthorizedUser a=actor(actorId,"CATALOG_CONFIG_WRITE");UUID i=institution(a,inst);requireEnabled(i,vaccine);validateType(r.fieldType());if(r.isDefault())local.lockActive(i,vaccine).stream().filter(x->x.getFieldType().equals(r.fieldType())).forEach(x->x.update(x.getValue(),x.getDisplayName(),x.getSortOrder(),false,x.isActive(),a.getId()));InstitutionVaccineOptionEntity x=local.save(new InstitutionVaccineOptionEntity(UUID.randomUUID(),i,vaccine,r.fieldType(),r.value(),r.displayName(),r.sortOrder(),r.isDefault(),null,a.getId(),Instant.now()));return new OptionResponse(x.getId(),vaccine,i,x.getFieldType(),x.getValue(),x.getDisplayName(),x.getSortOrder(),x.isDefault(),x.isActive(),null,x.getVersion());}
 @Transactional public OptionResponse updateOption(UUID actorId,UUID inst,UUID vaccine,UUID id,OptionRequest r){AuthorizedUser a=actor(actorId,"CATALOG_CONFIG_WRITE");UUID i=institution(a,inst);requireEnabled(i,vaccine);validateType(r.fieldType());InstitutionVaccineOptionEntity x=local.findByIdAndInstitutionIdAndVaccineId(id,i,vaccine).orElseThrow(()->new IllegalArgumentException("Opcion local no existe."));if(x.getVersion()!=r.version())throw new com.pai.api.catalog.exception.OptimisticCatalogException("La opcion fue modificada por otro usuario.");if(r.isDefault())local.lockActive(i,vaccine).stream().filter(y->y.getFieldType().equals(r.fieldType())&&!y.getId().equals(id)).forEach(y->y.update(y.getValue(),y.getDisplayName(),y.getSortOrder(),false,y.isActive(),a.getId()));x.update(r.value(),r.displayName(),r.sortOrder(),r.isDefault(),r.isActive(),a.getId());return new OptionResponse(x.getId(),vaccine,i,x.getFieldType(),x.getValue(),x.getDisplayName(),x.getSortOrder(),x.isDefault(),x.isActive(),x.getSourceTemplateId(),x.getVersion());}
  @Transactional public void deleteOption(UUID actorId,UUID inst,UUID vaccine,UUID id,long version){AuthorizedUser a=actor(actorId,"CATALOG_CONFIG_WRITE");UUID i=institution(a,inst);requireEnabled(i,vaccine);InstitutionVaccineOptionEntity x=local.findByIdAndInstitutionIdAndVaccineId(id,i,vaccine).orElseThrow(()->new IllegalArgumentException("Opcion local no existe."));if(x.getVersion()!=version)throw new com.pai.api.catalog.exception.OptimisticCatalogException("La opcion fue modificada por otro usuario.");x.update(x.getValue(),x.getDisplayName(),x.getSortOrder(),false,false,a.getId());}
  @Transactional(readOnly=true) public List<OptionResponse> suggested(UUID actorId,UUID inst,UUID vaccine){AuthorizedUser a=actor(actorId,"CATALOG_CONFIG_READ");UUID i=institution(a,inst);Set<String> existing=new HashSet<>(local.findByInstitutionIdAndVaccineIdAndActiveTrueOrderBySortOrderAscDisplayNameAsc(i,vaccine).stream().map(x->x.getValueNormalized()).toList());return templates.findByVaccineIdAndActiveTrueOrderBySortOrderAscDisplayNameAsc(vaccine).stream().filter(t->!existing.contains(t.getValueNormalized())).map(t->new OptionResponse(t.getId(),vaccine,i,t.getFieldType(),t.getValue(),t.getDisplayName(),t.getSortOrder(),false,true,t.getId(),0)).toList();}
  @Transactional public List<OptionResponse> importSuggested(UUID actorId,UUID inst,UUID vaccine){AuthorizedUser a=actor(actorId,"CATALOG_CONFIG_WRITE");UUID i=institution(a,inst);requireEnabled(i,vaccine);Set<String> existing=new HashSet<>(local.findByInstitutionIdAndVaccineIdAndActiveTrueOrderBySortOrderAscDisplayNameAsc(i,vaccine).stream().map(InstitutionVaccineOptionEntity::getValueNormalized).toList());List<OptionResponse> out=new ArrayList<>();for(VaccineOptionTemplateEntity t:templates.findByVaccineIdAndActiveTrueOrderBySortOrderAscDisplayNameAsc(vaccine))if(existing.add(t.getValueNormalized())){try{InstitutionVaccineOptionEntity x=local.saveAndFlush(new InstitutionVaccineOptionEntity(UUID.randomUUID(),i,vaccine,t.getFieldType(),t.getValue(),t.getDisplayName(),t.getSortOrder(),false,t.getId(),a.getId(),Instant.now()));out.add(new OptionResponse(x.getId(),vaccine,i,x.getFieldType(),x.getValue(),x.getDisplayName(),x.getSortOrder(),false,true,x.getSourceTemplateId(),x.getVersion()));}catch(org.springframework.dao.DataIntegrityViolationException ignored){}}return out;}
  private void validateType(String type){if(!Set.of("laboratory","syringe","dropper","observation").contains(type))throw new IllegalArgumentException("Tipo de opcion local invalido.");}
  private void requireEnabled(UUID institution,UUID vaccine){if(relations.findByInstitutionIdAndVaccineId(institution,vaccine).filter(x->x.isEnabled()).isEmpty())throw new IllegalArgumentException("La vacuna no esta habilitada en la institucion.");}
}
